cc_binary(
    name = "raymond4",
    srcs = ["raymond4.cpp"],
    deps = [
        "//src/lib/image",
        "//src/lib/image:camera",
        "//src/lib/math",
        "//src/lib/world",
    ],
)

cc_binary(
    name = "raymond5",
    srcs = ["raymond5.cpp"],
    deps = [
        "//src/lib/image",
        "//src/lib/image:camera",
        "//src/lib/math",
        "//src/lib/world",
    ],
)
