cc_library(
    name = "ray",
    srcs = [
    ],
    hdrs = [
        "ray.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/lib/types:the_types",
    ],
)

cc_library(
    name = "vec3",
    srcs = [
    ],
    hdrs = [
        "vec3.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
    ],
)

cc_library(
    name = "hittable",
    srcs = [
    ],
    hdrs = [
        "hittable.hpp",
        "hittable_list.hpp",
        "sphere.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/lib/geometry:interval",
        "//src/lib/geometry:ray",
        "//src/lib/types:the_types",
    ],
)

cc_library(
    name = "my_math",
    srcs = [
    ],
    hdrs = [
        "my_math.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/lib/types:the_types",
    ],
)

cc_library(
    name = "interval",
    srcs = [
    ],
    hdrs = [
        "interval.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/lib/geometry:my_math",
        "//src/lib/types:the_types",
    ],
)
