cc_library(
    name = "ray",
    srcs = [
    ],
    hdrs = [
        "ray.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/lib/types:the_types",
    ],
)

cc_library(
    name = "vec3",
    srcs = [
    ],
    hdrs = [
        "vec3.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
    ],
)
