cc_binary(
    name = "debra",
    srcs = ["debra.cpp"],
    deps = [
        "//src/lib/gui",
        "//src/lib/image",
        "//src/lib/image:camera",
        "//src/lib/math",
        "//src/lib/world",
    ],
)
