cc_library(
    name = "math",
    srcs = [
        "src/interval.cpp",
    ],
    hdrs = [
        "common.hpp",
        "interval.hpp",
        "my_math.hpp",
        "vec3.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
    ],
)
