cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cpp"],
    deps = [
        "//src/lib/image",
        "//src/lib/math",
    ],
)

cc_binary(
    name = "raymond",
    srcs = ["raymond.cpp"],
    deps = [
        "//src/lib/image",
        "//src/lib/math",
        "//src/lib/world",
    ],
)

cc_binary(
    name = "raymond2",
    srcs = ["raymond2.cpp"],
    deps = [
        "//src/lib/image",
        "//src/lib/image:camera",
        "//src/lib/math",
        "//src/lib/world",
    ],
)
