cc_library(
    name = "the_types",
    srcs = [
    ],
    hdrs = [
        "color.hpp",
        "the_types.hpp",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/lib/geometry:vec3",
    ],
)
